development:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: todolist_rails_dev

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: todolist_rails_production